### ISSUE TITLE
What is the relation to https://github.com/raystubbs/subzero?

### ISSUE THREAD

**Issue by simongray** [raystubbs/zero#38]
Since it isn't explained anywhere in the README (from what I can tell).

**Comment by raystubbs** [comment]
Good question.  Should probably find a place to put it... maybe a FAQ.

Basically all the stuff that is in SubZero was once in Zero.

SubZero now implements the basic web component and HTML rendering logic.  Also, a simple data store that can keep track of which paths are updated (this holds the library state).

This stuff seemed useful in its own right.  Tying it to Zero's state management system and all the other extras  seemed like an undesirable constraint.  This way other state management systems can be tacked onto SubZero, other libraries can build on it.

Zero adds state management and various utilities on top of it.

**Comment by simongray** [comment]
Thanks for answering and sorry if I abused the issue system :)

**Comment by raystubbs** [comment]
Haha, no worries.  I think issues are a good place to ask questions.
